apiVersion: apps/v1
kind: Deployment
metadata:
  name: smf
  labels:
    app: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smf
  template:
    metadata:
      labels:
        app: smf
    spec:
      containers:
      - name: smf
        image: {{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}
        env:
        - name: COMPONENT_NAME
          value: smf
---
apiVersion: v1
kind: Service
metadata:
  name: smf
spec:
  selector:
    app: smf
  ports:
  - port: 7777
    targetPort: 7777
