apiVersion: v1
kind: Service
metadata:
  name: open5gs-mongo-custom
spec:
  selector:
    app: open5gs-mongo-custom
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: open5gs-mongo-custom
spec:
  serviceName: open5gs-mongo-custom
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-mongo-custom
  template:
    metadata:
      labels:
        app: open5gs-mongo-custom
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
