apiVersion: v1
kind: ConfigMap
metadata:
  name: srsran-cu-config
data:
  cu.yml: |
    cu_cp:
      f1ap:
        bind_addr: 10.100.50.251
      amf:
        addr: 10.100.50.249
        bind_addr: 10.100.50.251
        supported_tracking_areas:
          - tac: 1
            plmn_list:
              - plmn: "20893"
                tai_slice_support_list:
                  - sst: 1
    log:
      filename: /tmp/cu.log
      all_level: warning
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: n2network-srsran-cu
spec:
  config: '{ "cniVersion": "0.3.1", "plugins": [ { "type": "ipvlan", "capabilities": { "ips": true }, "master": "enp3s0", "mode": "l2", "ipam": { "type": "static", "routes": [ { "dst": "0.0.0.0/0", "gw": "10.100.50.254" } ] } } ] }'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srsran-cu
  labels:
    app: srsran-cu
    ran-type: oran
    component: cu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srsran-cu
  template:
    metadata:
      labels:
        app: srsran-cu
        ran-type: oran
        component: cu
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "n2network-srsran-cu",
            "ips": [ "10.100.50.251/29" ],
            "gateway": [ "10.100.50.254" ] }
        ]'
    spec:
      containers:
      - name: cu
        image: ghcr.io/herlesupreeth/docker_srsran:master
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["srscu"]
        args: ["-c", "/mnt/srsran/cu.yml"]
        volumeMounts:
        - name: cu-config
          mountPath: /mnt/srsran
      volumes:
      - name: cu-config
        configMap:
          name: srsran-cu-config
---
apiVersion: v1
kind: Service
metadata:
  name: srsran-cu
spec:
  selector:
    app: srsran-cu
  ports:
  - name: ngap
    port: 38412
    targetPort: 38412
    protocol: SCTP
  - name: f1c
    port: 38472
    targetPort: 38472
    protocol: SCTP
