apiVersion: v1
kind: ServiceAccount
metadata:
  name: ran-exporter
  namespace: c63ff4ec-6bd4-46bc-90a2-d45fb0809c2c
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ran-exporter-pod-reader
  namespace: c63ff4ec-6bd4-46bc-90a2-d45fb0809c2c
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ran-exporter-pod-reader
  namespace: c63ff4ec-6bd4-46bc-90a2-d45fb0809c2c
subjects:
- kind: ServiceAccount
  name: ran-exporter
  namespace: c63ff4ec-6bd4-46bc-90a2-d45fb0809c2c
roleRef:
  kind: Role
  name: ran-exporter-pod-reader
  apiGroup: rbac.authorization.k8s.io
