apiVersion: v1
kind: Service
metadata:
  name: ims
spec:
  selector:
    app: ims
  clusterIP: {{ .Values.pcscfServiceIP }}
  ports:
  - {name: sip-pcscf-udp, port: 5060, protocol: UDP}
  - {name: sip-pcscf-tcp, port: 5060, protocol: TCP}
  - {name: sip-icscf, port: 4060, protocol: UDP}
  - {name: sip-scscf, port: 6060, protocol: UDP}
  - {name: pyhss-api, port: 8080, protocol: TCP}
