apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-cu-config
data:
  gnb.conf: |
    # SPDX-License-Identifier: LicenseRef-CSSL-1.0
    
    Active_gNBs = ( "cu-rfsim");
    # Asn1_verbosity, choice in: none, info, annoying
    Asn1_verbosity = "none";
    
    gNBs =
    (
     {
        ////////// Identification parameters:
        gNB_ID = 0xe00;
        gNB_name  =  "cu-rfsim";
    
        // Tracking area code, 0x0000 and 0xfffe are reserved values
        tracking_area_code  =  1;
        plmn_list = ({ mcc = 208; mnc = 93; mnc_length = 2; snssaiList = ({ sst = 1; }) });
    
        nr_cellid = 12345678L;
    
        tr_s_preference = "f1";
    
        local_s_address = "10.100.50.252";
        remote_s_address = "0.0.0.0"; # multiple DUs
        local_s_portd       = 2152;
        remote_s_portd      = 2152;
    
    
        # ------- SCTP definitions
        SCTP :
        {
            # Number of streams to use in input/output
            SCTP_INSTREAMS  = 2;
            SCTP_OUTSTREAMS = 2;
        };
    
    
        ////////// AMF parameters:
        amf_ip_address = ({ ipv4 = "10.100.50.249"; });
    
        NETWORK_INTERFACES :
        {
            GNB_IPV4_ADDRESS_FOR_NG_AMF = "10.100.50.252/29";
            GNB_IPV4_ADDRESS_FOR_NGU = "10.100.50.252/29";
            GNB_PORT_FOR_S1U                         = 2152; # Spec 2152
        };
      }
    );
    
    security = {
      # preferred ciphering algorithms
      # the first one of the list that an UE supports in chosen
      # valid values: nea0, nea1, nea2, nea3
      ciphering_algorithms = ( "nea0" );
    
      # preferred integrity algorithms
      # the first one of the list that an UE supports in chosen
      # valid values: nia0, nia1, nia2, nia3
      integrity_algorithms = ( "nia2", "nia0" );
    
      # setting 'drb_ciphering' to "no" disables ciphering for DRBs, no matter
      # what 'ciphering_algorithms' configures; same thing for 'drb_integrity'
      drb_ciphering = "yes";
      drb_integrity = "no";
    };
    
    log_config : {
      global_log_level = "info";
      pdcp_log_level = "info";
      rrc_log_level = "info";
      f1ap_log_level = "info";
      ngap_log_level = "info";
    };
    
    e2_agent = {
      near_ric_ip_addr = "127.0.0.1";
      sm_dir = "/usr/local/lib/flexric/"
    };
    
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: n2network-oai-cu
spec:
  config: '{ "cniVersion": "0.3.1", "plugins": [ { "type": "ipvlan", "capabilities": { "ips": true }, "master": "enp3s0", "mode": "l2", "ipam": { "type": "static", "routes": [ { "dst": "0.0.0.0/0", "gw": "10.100.50.254" } ] } } ] }'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-cu
  labels:
    app: oai-cu
    ran-type: oran
    component: cu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-cu
  template:
    metadata:
      labels:
        app: oai-cu
        ran-type: oran
        component: cu
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "n2network-oai-cu",
            "ips": [ "10.100.50.252/29" ],
            "gateway": [ "10.100.50.254" ] }
        ]'
    spec:
      containers:
      - name: cu
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: cu-config
          mountPath: /opt/oai-gnb/etc/gnb.conf
          subPath: gnb.conf
      volumes:
      - name: cu-config
        configMap:
          name: oai-cu-config
---
apiVersion: v1
kind: Service
metadata:
  name: oai-cu
spec:
  selector:
    app: oai-cu
  ports:
  - name: ngap
    port: 38412
    targetPort: 38412
    protocol: SCTP
  - name: f1
    port: 2152
    targetPort: 2152
    protocol: UDP
