apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-du-config
data:
  gnb.yaml: |
    Active_gNBs:
    - oai-du
    Asn1_verbosity: none
    gNBs:
    - gNB_ID: 0xe00
      gNB_name: oai-du
      tracking_area_code: 1
      plmn_list:
        - mcc: 208
          mnc: 93
          mnc_length: 2
          snssaiList:
            - sst: 1
              sd: 0x010203
      nr_cellid: 12345678
      min_rxtxtime: 6
      NETWORK_INTERFACES:
        GNB_INTERFACE_NAME_FOR_NG_AMF: eth0
        GNB_IPV4_ADDRESS_FOR_NG_AMF: 0.0.0.0
        GNB_INTERFACE_NAME_FOR_NGU: eth0
        GNB_IPV4_ADDRESS_FOR_NGU: 0.0.0.0
        GNB_PORT_FOR_S1U: 2152
      f1_interface:
        ipv4_f1_cu: 10.100.50.252
        ipv4_f1_du: 10.100.50.253
        f1_port: 38472
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: n2network-oai-du
spec:
  config: '{ "cniVersion": "0.3.1", "plugins": [ { "type": "ipvlan", "capabilities": { "ips": true }, "master": "enp3s0", "mode": "l2", "ipam": { "type": "static", "routes": [ { "dst": "0.0.0.0/0", "gw": "10.100.50.254" } ] } } ] }'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-du
  labels:
    app: oai-du
    ran-type: oran
    component: du
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-du
  template:
    metadata:
      labels:
        app: oai-du
        ran-type: oran
        component: du
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "n2network-oai-du",
            "ips": [ "10.100.50.253/29" ],
            "gateway": [ "10.100.50.254" ] }
        ]'
    spec:
      containers:
      - name: du
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: true
        env:
        - name: COMPONENT_NAME
          value: du
        volumeMounts:
        - name: du-config
          mountPath: /opt/oai-gnb/etc/gnb.yaml
          subPath: gnb.yaml
      volumes:
      - name: du-config
        configMap:
          name: oai-du-config
---
apiVersion: v1
kind: Service
metadata:
  name: oai-du
spec:
  selector:
    app: oai-du
  ports:
  - name: f1
    port: 38472
    targetPort: 38472
    protocol: SCTP
