apiVersion: v1
kind: ConfigMap
metadata:
  name: srsran-du-config
data:
  du.yml: |
    f1ap:
      cu_cp_addr: 10.100.50.251
      bind_addr: 10.100.50.252
    f1u:
      bind_port: 2152
      peer_port: 2152
    cell_cfg:
      dl_arfcn: 632628
      band: 78
      channel_bandwidth_MHz: 20
      common_scs: 30
      plmn: "20893"
      tac: 1
      pci: 1
    ru_sdr:
      device_driver: zmq
      device_args: tx_port=tcp://127.0.0.1:2000,rx_port=tcp://127.0.0.1:2001
      srate: 23.04
      tx_gain: 75
      rx_gain: 75
    log:
      filename: /tmp/du.log
      all_level: warning
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: n2network-srsran-du
spec:
  config: '{ "cniVersion": "0.3.1", "plugins": [ { "type": "ipvlan", "capabilities": { "ips": true }, "master": "enp3s0", "mode": "l2", "ipam": { "type": "static", "routes": [ { "dst": "0.0.0.0/0", "gw": "10.100.50.254" } ] } } ] }'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srsran-du
  labels:
    app: srsran-du
    ran-type: oran
    component: du
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srsran-du
  template:
    metadata:
      labels:
        app: srsran-du
        ran-type: oran
        component: du
      annotations:
        sidecar.istio.io/inject: "false"
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "n2network-srsran-du",
            "ips": [ "10.100.50.252/29" ],
            "gateway": [ "10.100.50.254" ] }
        ]'
    spec:
      containers:
      - name: du
        image: ghcr.io/herlesupreeth/docker_srsran:master
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["srsdu"]
        args: ["-c", "/mnt/srsran/du.yml"]
        volumeMounts:
        - name: du-config
          mountPath: /mnt/srsran
      volumes:
      - name: du-config
        configMap:
          name: srsran-du-config
---
apiVersion: v1
kind: Service
metadata:
  name: srsran-du
spec:
  selector:
    app: srsran-du
  ports:
  - name: f1c
    port: 38472
    targetPort: 38472
    protocol: SCTP
  - name: f1u
    port: 2152
    targetPort: 2152
    protocol: UDP
