image:
  repository: ghcr.io/herlesupreeth/docker_srsran
  tag: master
  pullPolicy: IfNotPresent

gnb:
  mcc: "208"
  mnc: "93"
  tac: 1
  plmn: "20893"
  amf:
    address: "10.100.50.249"
    port: 38412
  radio:
    device: zmq
    dlArfcn: 632628
    band: 78
    bandwidth: 20
    scs: 30

network:
  masterIf: enp3s0

ran:
  type: cran
