image:
  repository: ghcr.io/herlesupreeth/docker_srsran
  tag: master
  pullPolicy: IfNotPresent

gnb:
  mcc: "208"
  mnc: "93"
  tac: 1
  plmn: "20893"
  amf:
    address: "open5gs-amf-ngap"
    port: 38412

network:
  masterIf: enp3s0

ran:
  type: cran
