image:
  repository: oaisoftwarealliance/oai-gnb
  tag: 2026.w25
  pullPolicy: IfNotPresent

du:
  mcc: "208"
  mnc: "93"
  tac: 1
  plmn: "20893"
  cu:
    address: "oai-cu"
    port: 38472

network:
  masterIf: enp3s0

ran:
  type: oran
  component: du
