apiVersion: v1
kind: ServiceAccount
metadata:
  name: oai-nr-ue
  namespace: PLACEHOLDER_NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oai-nr-ue-pod-reader
  namespace: PLACEHOLDER_NAMESPACE
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oai-nr-ue-pod-reader
  namespace: PLACEHOLDER_NAMESPACE
subjects:
- kind: ServiceAccount
  name: oai-nr-ue
  namespace: PLACEHOLDER_NAMESPACE
roleRef:
  kind: Role
  name: oai-nr-ue-pod-reader
  apiGroup: rbac.authorization.k8s.io
